# syntax=docker/dockerfile:1.4

FROM python:3.9-slim
RUN apt update && apt install gcc -y

RUN apt-get update && apt-get install -y --no-install-recommends build-essential

WORKDIR /launch

COPY --link requirements.txt ./
RUN pip install -r requirements.txt

COPY --link job.py ./
ENTRYPOINT ["python3", "job.py"]
