scheduler:
   job: griffin_wb/proj/job-optuna-scheduler_latest:latest
   resource: local-container

   # optuna specific config
   settings:
      pruner:
         type: PercentilePruner
         args:
            n_startup_trials: 2
            n_min_trials: 1
            percentile: 0.25  # top 25% kept

job: griffin_wb/proj/job-source-proj-simple.py:latest
run_cap: 2
metric:
  goal: maximize
  name: val_acc

parameters:
   epochs:
      values: [10, 25, 100, 200]
