version: 2.1

jobs:
  build_and_push_image:
    parameters:
      subdir:
        type: string
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Check for Changes in Subdirectory
          command: |
            PARENT_DIR=$(dirname << parameters.subdir >>)
            if git diff --name-only HEAD~1...HEAD | grep -q '^<< parameters.subdir >>' \
              || { [[ "$PARENT_DIR" == "jobs/inspect_ai_evals" ]] && git diff --name-only HEAD~1...HEAD -- ':(glob)jobs/inspect_ai_evals/*' ':(exclude)jobs/inspect_ai_evals/api_model/**' ':(exclude)jobs/inspect_ai_evals/model_checkpoint/**' | grep -q .; }; then
              echo "Changes detected in << parameters.subdir >>, building Docker image."
              echo $DOCKERHUB_TOKEN | docker login --username davidwandb --password-stdin
              docker buildx create --platform linux/amd64,linux/arm64 --use
              
              # Special handling for inspect_ai_evals subdirectories since they have shared code across jobs
              if [[ "<< parameters.subdir >>" == jobs/inspect_ai_evals/* ]]; then
                subdir_name=$(basename << parameters.subdir >>)
                cd jobs/inspect_ai_evals
                image_name=$(echo "<< parameters.subdir >>" | sed 's/jobs\//job_/g; s/\//_/g')
                docker buildx build --platform linux/amd64,linux/arm64 -t wandb/$image_name:$CIRCLE_BRANCH -t wandb/$image_name:$CIRCLE_SHA1 --push --file ${subdir_name}/Dockerfile.wandb .
              else
                cd << parameters.subdir >>
                image_name=$(echo "<< parameters.subdir >>" | sed 's/jobs\//job_/g; s/services\//service_/g; s/\//_/g')
                docker buildx build --platform linux/amd64,linux/arm64 -t wandb/$image_name:$CIRCLE_BRANCH -t wandb/$image_name:$CIRCLE_SHA1 --push --file Dockerfile.wandb .
              fi
            else
              echo "No changes in << parameters.subdir >>, skipping build."
            fi

workflows:
  build_and_deploy:
    jobs:
      - build_and_push_image:
          filters:
            branches:
              only: main
          matrix:
            parameters:
              subdir:
                [
                  "jobs/deploy_to_nvidia_triton",
                  "jobs/deploy_to_sagemaker_endpoints",
                  "jobs/distributed_test",
                  "jobs/fashion_mnist_train",
                  "jobs/github_actions_workflow_dispatch",
                  "jobs/gpu_optimize_with_tensor_rt",
                  "jobs/hello_world",
                  "jobs/http_webhook",
                  "jobs/inspect_ai_evals/model_checkpoint",
                  "jobs/inspect_ai_evals/api_model",
                  "jobs/msft_teams_webhook",
                  "jobs/openai_evals",
                  "jobs/sql_query",
                  "jobs/stable_diffusion_inference",
                  "jobs/sweep_schedulers/optuna_scheduler",
                  "jobs/sweep_schedulers/wandb_scheduler",
                  "services/vllm_server",
                ]
