version: 2.1

jobs:
  build:
    resource_class: medium
    docker:
      - image: cimg/base:2023.03
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - checkout
      - run:
          name: Build Docker image
          command: |
            docker buildx create --platform linux/amd64,linux/arm64 --use
            echo $DOCKERHUB_TOKEN | docker login --username davidwandb --password-stdin
            ./docker_build.py

workflows:
  build:
    jobs:
      - hold:
          type: approval
      - build:
          requires:
            - hold
