run_name: Deploy PyTorch Model
config:
  artifact: "wandb-artifact://megatruong/ptl-testing2/model-vgw632i7:v0"
  framework: "pytorch"
  framework_version: "1.12"
  python_version: "py38"
  sagemaker_role: "arn:aws:iam::687678353814:role/sagemaker"
  sagemaker_bucket: "sagemaker-us-west-2-687678353814"
  instance_type: "ml.c5.xlarge"
  instance_count: 1
  sagemaker_model_setup_kwargs: {}
  sagemaker_model_deployment_kwargs: {}
