run_name: Deploy TensorFlow Model
config:
  artifact: "wandb-artifact://megatruong/fashion-mnist-keras-triton/model-sage-feather-1:v2"
  framework: "tensorflow"
  framework_version: "2.10.0"
  python_version: "py38"
  sagemaker_role: "arn:aws:iam::687678353814:role/sagemaker"
  sagemaker_bucket: "sagemaker-us-west-2-687678353814"
  instance_type: "ml.c5.xlarge"
  instance_count: 1
  sagemaker_model_setup_kwargs: {}
  sagemaker_model_deployment_kwargs: {}
