run_name: American Bar Association - 01
config:
  eval: aba_mrpc_true_false
  model:
    name: gpt-3.5-turbo
    override_prompt: You are clueless.  Answer randomly!
  registry: "wandb/jobs/openai_evals_registry:latest"
  oaieval_settings:
    max_samples: 10
