run_name: Japanese Translation - 03
config:
  eval: manga-translation-bubble
  model:
    name: gpt-3.5-turbo
    override_prompt: Imagine you are a translator. Give faithful translations of the following Japanese text to English. Do not think out loud.
  registry: "wandb/jobs/openai_evals_registry:latest"
  oaieval_settings:
    max_samples: 10
