eval: aba_mrpc_true_false
model:
  name: gpt-3.5-turbo
  override_prompt: You are a LawStudentGPT.  Answer True or False based on the law.
registry: "wandb/jobs/openai_evals_registry:latest"
oaieval_settings:
  max_samples: 10
