name: Build Jobs
on: [workflow_dispatch, push]
jobs:
  find-directories:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.get-dirs.outputs.dirs }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get Directories
        id: get-dirs
        run: |
          dirs=$(find /path/to/directory -type d -mindepth 1 -maxdepth 1)
          echo "::set-output name=dirs::${dirs}"

  repeat-steps:
    needs: find-directories
    strategy:
      matrix:
        dir: ${{ fromJson(needs.find-directories.outputs.dirs) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Directory
        run: |
          cd ${{ matrix.dir }}

      - name: Step 1
        run: |
          # Execute step 1 here

      - name: Step 2
        run: |
          # Execute step 2 here

      - name: Step 3
        run: |
          # Execute step 3 here

      - name: Go Back to Root
        run: |
          cd ..

      # - name: Docker login
      #   run: |
      #     docker login -u itsandrewtruong -p "${{ secrets.DOCKERHUB_TOKEN }}"

      # - name: Build everything
      #   run: |
      #     docker build -t openai-eval jobs/openai_eval

      # - name: Tag and push
      #   run: |
      #     docker tag openai-eval itsandrewtruong/openai-eval-gh:latest && \
      #     docker push itsandrewtruong/openai-eval-gh