name: Build Jobs
on: [workflow_dispatch, push]

jobs:
  find-directories:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.get-dirs.outputs.dirs }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: List Directories
        id: get-dirs
        run: |
          echo "dirs=$(ls jobs | jq -Rsc 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  repeat-steps:
    needs: find-directories
    strategy:
      max-parallel: 1
      matrix:
        # dir: ${{ fromJson(needs.find-directories.outputs.dirs) }}
        dir: ["openai_eval"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Docker login
        run: |
          docker login -u cvpwb -p "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Setup Docker Buildx
        run: |
          docker buildx create --platform linux/amd64,linux/arm64 --use

      - name: Build and push
        run: |
          docker buildx build --cache-from type=gha --cache-to type=gha --platform linux/amd64,linux/arm64 --push -t wandb/job_${{ matrix.dir }}:$TAG jobs/${{ matrix.dir }}

      - name: Wipe the cache
        run: |
          docker buildx prune -af
