name: Build Jobs
on: [workflow_dispatch, push]
jobs:
  find-directories:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.get-dirs.outputs.dirs }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: List Directories
        run: |
          directories=$(ls jobs | jq -Rsc 'split("\n")[:-1]')
          echo "$directories" >> $GITHUB_OUTPUT

  repeat-steps:
    needs: find-directories
    strategy:
      matrix:
        dir: ${{ fromJson(needs.find-directories.outputs.dirs) }}
        # dir: ["openai_eval"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Docker login
        run: |
          docker login -u itsandrewtruong -p "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Setup Docker Buildx
        run: |
          docker buildx create --name bobthebuilder --platform linux/amd64,linux/arm64 --use

      - name: Build and push
        run: |
          echo $(ls $(pwd))
          docker buildx build --cache-from type=gha --cache-to type=gha --platform linux/amd64,linux/arm64 --push -t itsandrewtruong/${{ matrix.dir }}:gh-test jobs/${{ matrix.dir }}
