name: Build Jobs
on: [workflow_dispatch, push]
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.get-dirs.outputs.dirs }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get Directories
        id: get-dirs
        run: |
          find jobs -type d -mindepth 1 -maxdepth 1 > dirs.txt
          echo ::set-output name=dirs::$(cat dirs.txt)

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        dir: ${{ fromJson(needs.setup.outputs.dirs) }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Directory to ${{ matrix.dir }}
        run: |
          cd ${{ matrix.dir }}

      - name: Test
        run: |
          pwd

      # - name: Docker login
      #   run: |
      #     docker login -u itsandrewtruong -p "${{ secrets.DOCKERHUB_TOKEN }}"

      # - name: Build everything
      #   run: |
      #     docker build -t openai-eval jobs/openai_eval

      # - name: Tag and push
      #   run: |
      #     docker tag openai-eval itsandrewtruong/openai-eval-gh:latest && \
      #     docker push itsandrewtruong/openai-eval-gh