name: Build Jobs
on: [workflow_dispatch, push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Use find command to get a list of all directories in the path
      - name: Find Directories
        id: dirs
        run: |
          find /path/to/directory -type d -mindepth 1 -maxdepth 1 > dirs.txt

      # Use a for loop to execute the steps for each directory
      - name: Repeat Steps for Directories
        run: |
          while read -r dir; do
            cd $dir
            # Execute the steps here
            echo "Executing steps for $dir"
            cd ..
          done < dirs.txt

      # - name: Docker login
      #   run: |
      #     docker login -u itsandrewtruong -p "${{ secrets.DOCKERHUB_TOKEN }}"

      # - name: Build everything
      #   run: |
      #     docker build -t openai-eval jobs/openai_eval

      # - name: Tag and push
      #   run: |
      #     docker tag openai-eval itsandrewtruong/openai-eval-gh:latest && \
      #     docker push itsandrewtruong/openai-eval-gh