name: Build Jobs
on: [workflow_dispatch, push]
jobs:
  find-directories:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.get-dirs.outputs.dirs }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get Directories
        id: get-dirs
        run: |
          dirs=$(find jobs -type d -mindepth 1 -maxdepth 1)
          echo "::set-output name=dirs::${dirs}"

  repeat-steps:
    needs: find-directories
    strategy:
      matrix:
        # dir: ${{ needs.find-directories.outputs.dirs }}
        dir: ["jobs/hello_world", "jobs/http_webhook"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Docker login
        run: |
          docker login -u itsandrewtruong -p "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Set Directory
        run: |
          cd ${{ matrix.dir }}

      - name: Setup Docker Buildx
        run: |
          docker buildx create --name bobthebuilder --platform linux/amd64,linux/arm64 && \
          docker buildx use bobthebuilder

      - name: Build and push
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 --push -t itsandrewtruong/${{ matrix.dir }}:gh-test ${{ matrix.dir }}

      # - name: Build everything
      #   run: |
      #     docker build -t openai-eval jobs/openai_eval

      # - name: Tag and push
      #   run: |
      #     docker tag openai-eval itsandrewtruong/openai-eval-gh:latest && \
      #     docker push itsandrewtruong/openai-eval-gh