run_name: Example
config:
  webhook_url: "https://sysadminwandb.webhook.office.com/webhookb2/1fc24ff9-fe1f-4cf2-ab3b-88d0189149fd@af722783-84b6-4adc-9c49-c792786eab4a/IncomingWebhook/11767fa7c40840e4bb52817bce8d59aa/44f0d0e4-adc1-4ca6-84bc-1768a8278b1f"
  title: "New model deployed!"
  artifact: "wandb-artifact://wandb/pytorch-lightning-e2e/nature-e1d5dg6m:latest"
  alias: "${alias}"
  text: "example text"
  link_button:
    { "text": "Review Deployed Model", "url": "https://www.wandb.ai" }
  color: "#00FF00"
  retry_settings:
    attempts: 3
    backoff:
      multiplier: 1
      max: 60
